module: MetricsViewer
author: Kamaal Farah
github_url: https://github.com/kamaal111/MetricsViewer
exclude:
  - Tests
copyright: "© 2021 Kamaal Farah under [open source license](https://github.com/kamaal111/MetricsViewer/blob/main/LICENSE)."
output: JazzyDocs
